// Code generated by MockGen. DO NOT EDIT.
// Source: ./daemon/internal/index/factory/factory_index.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	dto "victord/daemon/internal/dto"
	factory "victord/daemon/internal/index/factory"

	gomock "github.com/golang/mock/gomock"
)

// MockIndexFactory is a mock of IndexFactory interface.
type MockIndexFactory struct {
	ctrl     *gomock.Controller
	recorder *MockIndexFactoryMockRecorder
}

// MockIndexFactoryMockRecorder is the mock recorder for MockIndexFactory.
type MockIndexFactoryMockRecorder struct {
	mock *MockIndexFactory
}

// NewMockIndexFactory creates a new mock instance.
func NewMockIndexFactory(ctrl *gomock.Controller) *MockIndexFactory {
	mock := &MockIndexFactory{ctrl: ctrl}
	mock.recorder = &MockIndexFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexFactory) EXPECT() *MockIndexFactoryMockRecorder {
	return m.recorder
}

// CreateIndexType mocks base method.
func (m *MockIndexFactory) CreateIndexType(arg0 *dto.CreateIndexRequest) (factory.GenericIndex, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIndexType", arg0)
	ret0, _ := ret[0].(factory.GenericIndex)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIndexType indicates an expected call of CreateIndexType.
func (mr *MockIndexFactoryMockRecorder) CreateIndexType(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIndexType", reflect.TypeOf((*MockIndexFactory)(nil).CreateIndexType), arg0)
}
