// Code generated by MockGen. DO NOT EDIT.
// Source: ./daemon/internal/store/service/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	models "victord/daemon/internal/index/models"

	gomock "github.com/golang/mock/gomock"
)

// MockIndexStore is a mock of IndexStore interface.
type MockIndexStore struct {
	ctrl     *gomock.Controller
	recorder *MockIndexStoreMockRecorder
}

// MockIndexStoreMockRecorder is the mock recorder for MockIndexStore.
type MockIndexStoreMockRecorder struct {
	mock *MockIndexStore
}

// NewMockIndexStore creates a new mock instance.
func NewMockIndexStore(ctrl *gomock.Controller) *MockIndexStore {
	mock := &MockIndexStore{ctrl: ctrl}
	mock.recorder = &MockIndexStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexStore) EXPECT() *MockIndexStoreMockRecorder {
	return m.recorder
}

// GetIndex mocks base method.
func (m *MockIndexStore) GetIndex(arg0 string) (*models.IndexResource, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndex", arg0)
	ret0, _ := ret[0].(*models.IndexResource)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetIndex indicates an expected call of GetIndex.
func (mr *MockIndexStoreMockRecorder) GetIndex(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndex", reflect.TypeOf((*MockIndexStore)(nil).GetIndex), arg0)
}

// GetIndexDims mocks base method.
func (m *MockIndexStore) GetIndexDims(indexName string) (uint16, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexDims", indexName)
	ret0, _ := ret[0].(uint16)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetIndexDims indicates an expected call of GetIndexDims.
func (mr *MockIndexStoreMockRecorder) GetIndexDims(indexName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexDims", reflect.TypeOf((*MockIndexStore)(nil).GetIndexDims), indexName)
}

// StoreIndex mocks base method.
func (m *MockIndexStore) StoreIndex(indexResource *models.IndexResource) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StoreIndex", indexResource)
}

// StoreIndex indicates an expected call of StoreIndex.
func (mr *MockIndexStoreMockRecorder) StoreIndex(indexResource interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreIndex", reflect.TypeOf((*MockIndexStore)(nil).StoreIndex), indexResource)
}
