// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: victord.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VictorService_CreateIndex_FullMethodName = "/pb.VictorService/CreateIndex"
)

// VictorServiceClient is the client API for VictorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VictorServiceClient interface {
	CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error)
}

type victorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVictorServiceClient(cc grpc.ClientConnInterface) VictorServiceClient {
	return &victorServiceClient{cc}
}

func (c *victorServiceClient) CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIndexResponse)
	err := c.cc.Invoke(ctx, VictorService_CreateIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VictorServiceServer is the server API for VictorService service.
// All implementations must embed UnimplementedVictorServiceServer
// for forward compatibility.
type VictorServiceServer interface {
	CreateIndex(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error)
	mustEmbedUnimplementedVictorServiceServer()
}

// UnimplementedVictorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVictorServiceServer struct{}

func (UnimplementedVictorServiceServer) CreateIndex(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIndex not implemented")
}
func (UnimplementedVictorServiceServer) mustEmbedUnimplementedVictorServiceServer() {}
func (UnimplementedVictorServiceServer) testEmbeddedByValue()                       {}

// UnsafeVictorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VictorServiceServer will
// result in compilation errors.
type UnsafeVictorServiceServer interface {
	mustEmbedUnimplementedVictorServiceServer()
}

func RegisterVictorServiceServer(s grpc.ServiceRegistrar, srv VictorServiceServer) {
	// If the following call pancis, it indicates UnimplementedVictorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VictorService_ServiceDesc, srv)
}

func _VictorService_CreateIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VictorServiceServer).CreateIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VictorService_CreateIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VictorServiceServer).CreateIndex(ctx, req.(*CreateIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VictorService_ServiceDesc is the grpc.ServiceDesc for VictorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VictorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VictorService",
	HandlerType: (*VictorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIndex",
			Handler:    _VictorService_CreateIndex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "victord.proto",
}
